### ISSUE TITLE
Throw helpful error if `url` query variable is used

### ISSUE THREAD

**Issue by Tohaker** [octokit/graphql.js#264] opened 2021-03-09 20:57 UTC
Hi, I'm trying to run the following query;
```
query GetCommitStatus($url: URI!) {
    resource(url: $url) {
      ... on Commit {
        status {
          state
        }
      }
    }
  }
```
I'm calling the GraphQL client with 
```ts
await graphqlClient<{ resource: Commit }>(getCommitStatus, {
        url: encodeURI(headCommitUrl),
      })
```

But I keep getting the following error:
```
[2021-03-09T20:43:37.452Z] Exception: GraphqlError: Variable $url of type URI! was provided invalid value
[2021-03-09T20:43:37.452Z] Stack: GraphqlError: Variable $url of type URI! was provided invalid value
[2021-03-09T20:43:37.452Z]     at /workspaces/merge_train/node_modules/@octokit/graphql/dist-node/index.js:69:13
[2021-03-09T20:43:37.453Z]     at processTicksAndRejections (internal/process/task_queues.js:93:5).
```

Trying the same query in GraphiQL with simply a String as the URL yields a successful response.
What do I need to do to properly format this URL?

I've tried
* `encodeURI`
* `encodeURIComponent`
* `new URL()`

**Comment by gr2m** [comment] 2021-03-09 21:03
The problem is that `url` is a special variable name that is used internally for the GraphQL endpoint URL. You should have gotten an explanatory error message, I'll have a look into it.

To resolve the problem, use a variable name other than `url`

**Comment by Tohaker** [comment] 2021-03-09 21:11
Thanks so much, all working now! Would definitely be helpful to get a better error message next time. :)

**Comment by gr2m** [comment] 2021-03-09 23:32
fixed via https://github.com/octokit/graphql.js/pull/265

**Closed** 2021-03-09 23:33 UTC
Labels: bug
